<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>ab65324f-3b88-4953-9f5c-9ed3d0ab4929</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="CloudinaryDotNet" Version="1.27.5" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.15" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<!-- Removed SQL Server provider -->
		<!-- <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.15" /> -->

		<!-- Added MySQL/MariaDB provider -->
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
	</ItemGroup>
</Project>
